version: '3.8'

services:
  credit-risk-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://localhost:5000
    volumes:
      - ./data:/app/data
    restart: unless-stopped 